//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "i2o.h"

@class NSArray, NSMutableArray, NSString;

@interface a3v : NSObject <i2o>
{
    struct dispatch_queue_s *_queue;
    NSMutableArray *_z3R;
}

- (void).cxx_destruct;
- (_Bool)n0B:(id)arg1;
- (void)p6F;
- (void)o1P:(id)arg1;
- (void)d1y:(id)arg1;
@property(readonly) NSArray *z3R;
- (id)z12:(id)arg1 e3S:(id)arg2;
- (id)b3F:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

