//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "i2o.h"

@class NSDateFormatter, NSString;

@interface b5d : NSObject <i2o>
{
    NSDateFormatter *_dateFormatter;
}

- (void).cxx_destruct;
- (id)b3F:(id)arg1;
- (id)initLf05:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

