//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "o2m.h"

#import "m31.h"

@class NSFileHandle, NSString, p6e;

@interface c5i : o2m <m31>
{
    id <j4c> _j4V;
    p6e *n9L;
    NSFileHandle *j9c;
    struct dispatch_source_s *f0a;
    struct dispatch_source_s *j6t;
    unsigned long long _m8Y;
    double _w6g;
    _Bool _z5b;
    _Bool _m37;
    id <j4c> j4V;
}

@property _Bool m37; // @synthesize m37=_m37;
@property _Bool z5b; // @synthesize z5b=_z5b;
@property(readonly, nonatomic) id <j4c> j4V; // @synthesize j4V;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *f7q;
- (void)i6b;
- (void)z5W:(id)arg1;
- (id)y6C;
- (id)q8L;
- (void)j9U;
- (void)i7s;
- (void)a2r;
- (void)d3OR:(CDUnknownBlockType)arg1;
- (void)o6W;
- (void)s3b;
@property double w6g;
@property unsigned long long m8Y;
- (void)dealloc;
- (id)initLa8z:(id)arg1;
- (id)init;

// Remaining properties
@property(retain, nonatomic) id <i2o> b9L;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) struct dispatch_queue_s *n50;
@property(readonly) Class superclass;

@end

