//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface c7y : NSObject
{
}

+ (void)o9J;
+ (void)t5y:(id)arg1;
+ (id)p1Q;
+ (void)w88;
+ (void)l1E:(id)arg1;
+ (void)q9y:(id)arg1 level:(unsigned long long)arg2;
+ (void)setLevel:(unsigned long long)arg1 s5a:(id)arg2;
+ (void)setLevel:(unsigned long long)arg1 forClass:(Class)arg2;
+ (unsigned long long)b3d:(id)arg1;
+ (unsigned long long)e7K:(Class)arg1;
+ (id)f2C;
+ (id)k4N;
+ (_Bool)n4G:(Class)arg1;
+ (void)n1r;
+ (void)log:(_Bool)arg1 message:(id)arg2;
+ (void)log:(_Bool)arg1 message:(id)arg2 level:(unsigned long long)arg3 flag:(unsigned long long)arg4 context:(int)arg5 file:(const char *)arg6 function:(const char *)arg7 line:(int)arg8 tag:(id)arg9;
+ (void)log:(_Bool)arg1 level:(unsigned long long)arg2 flag:(unsigned long long)arg3 context:(int)arg4 file:(const char *)arg5 function:(const char *)arg6 line:(int)arg7 tag:(id)arg8 format:(id)arg9 args:(struct __va_list_tag [1])arg10;
+ (void)log:(_Bool)arg1 level:(unsigned long long)arg2 flag:(unsigned long long)arg3 context:(int)arg4 file:(const char *)arg5 function:(const char *)arg6 line:(int)arg7 tag:(id)arg8 format:(id)arg9;
+ (void)m0E:(id)arg1 a6Z:(_Bool)arg2;
+ (id)i0G;
+ (void)l54;
+ (void)v14:(id)arg1;
+ (void)m7o:(id)arg1 v7Y:(unsigned long long)arg2;
+ (void)m7o:(id)arg1;
+ (void)applicationWillTerminate:(id)arg1;
+ (struct dispatch_queue_s *)n78;
+ (void)initialize;

@end

