//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "i2o.h"

@class NSDateFormatter, NSMutableDictionary, NSString;

@interface g1M : NSObject <i2o>
{
    NSString *b9d;
    int x3X;
    NSDateFormatter *w31;
    int _lock;
    unsigned long long _h3a;
    unsigned long long _h6N;
    NSMutableDictionary *_replacements;
}

@property unsigned long long h6N; // @synthesize h6N=_h6N;
@property unsigned long long h3a; // @synthesize h3a=_h3a;
- (void).cxx_destruct;
- (void)u35:(id)arg1;
- (void)i8R:(id)arg1;
- (id)b3F:(id)arg1;
- (id)d6P:(id)arg1;
- (id)stringFromDate:(id)arg1;
- (void)setReplacementString:(id)arg1 n1R:(id)arg2;
- (id)c5y:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

