//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, p84;

@protocol i2o <NSObject>
- (NSString *)b3F:(p84 *)arg1;

@optional
- (void)u35:(id <m31>)arg1;
- (void)i8R:(id <m31>)arg1;
@end

