//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@protocol j4c <NSObject>
@property unsigned long long i73;
@property unsigned long long q0O;
- (NSString *)c1h;
- (NSArray *)x21;
- (NSArray *)j7P;
- (NSArray *)l6z;
- (NSArray *)s0H;
- (NSArray *)g65;
- (NSArray *)g0b;
- (NSString *)c6v;

@optional
- (void)o0n:(NSString *)arg1;
- (void)w3h:(NSString *)arg1;
@end

