//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "o2m.h"

@interface k1n : o2m
{
    unsigned long long _k4n;
    double _l8H;
    double _e1l;
    double _y6O;
    _Bool _p1H;
    _Bool x2C;
    unsigned long long h0Y;
    unsigned long long n0Y;
    struct dispatch_source_s *d8N;
    unsigned long long l3L;
    struct dispatch_source_s *c6U;
}

- (void)flush;
- (void)z5W:(id)arg1;
- (void)i6b;
- (void)e9v;
- (void)p0F;
- (void)b4K;
@property _Bool p1H;
@property double y6O;
@property double e1l;
@property double l8H;
@property unsigned long long k4n;
- (void)g15;
- (void)q4p;
- (void)f9C;
- (void)y3D;
- (void)q8w;
- (void)e54;
- (void)z0C;
- (void)q4E;
- (void)g3b;
- (void)z3F;
- (void)v60;
- (_Bool)l6U:(id)arg1;
- (void)dealloc;
- (id)init;

@end

