//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "j4c.h"

@class NSString;

@interface l29 : NSObject <j4c>
{
    unsigned long long _q0O;
    unsigned long long _i73;
    NSString *y1o;
    NSString *u1r;
}

@property unsigned long long i73; // @synthesize i73=_i73;
@property unsigned long long q0O; // @synthesize q0O=_q0O;
- (void).cxx_destruct;
- (id)x62;
- (id)c1h;
@property(readonly, copy) NSString *z15;
- (id)x21;
- (id)j7P;
- (id)l6z;
- (id)s0H;
- (id)g65;
- (id)g0b;
- (id)n1w;
- (_Bool)o3G:(id)arg1;
- (id)c6v;
- (id)l0Q;
- (void)a72;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (id)initLt32:(id)arg1 c5L:(id)arg2;
- (id)initLt32:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

