//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface n2Y : NSObject
{
    unsigned long long mask;
    int context;
    unsigned char x3y;
    unsigned char k5c;
    unsigned char n86;
    unsigned char w6D;
    unsigned char v2E;
    unsigned char p2g;
    unsigned long long w8x;
    NSString *u2D;
    unsigned long long n20;
    NSString *o30;
    char l1k[24];
    unsigned long long d4F;
    char e9N[24];
    unsigned long long t4F;
    char n6S[8];
    unsigned long long a9r;
}

- (void).cxx_destruct;
- (id)description;
- (id)initLg91:(id)arg1 backgroundColor:(id)arg2 flag:(unsigned long long)arg3 context:(int)arg4;

@end

