//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "m31.h"

@class NSString;

@interface o2m : NSObject <m31>
{
    id <i2o> _b9L;
    struct dispatch_queue_s *_n50;
}

@property(nonatomic) struct dispatch_queue_s *n50; // @synthesize n50=_n50;
- (void).cxx_destruct;
@property(readonly, nonatomic, getter=isV1R) _Bool v1R;
@property(readonly, nonatomic, getter=isG56) _Bool g56;
@property(readonly, nonatomic) NSString *f7q;
@property(retain, nonatomic) id <i2o> b9L;
- (void)z5W:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

