//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSDictionary, NSString;

@interface p6e : NSObject
{
    NSString *_filePath;
    NSString *_fileName;
    NSDictionary *_fileAttributes;
    NSDate *_creationDate;
    NSDate *_modificationDate;
    unsigned long long _fileSize;
    NSString *filePath;
}

+ (id)d0q:(id)arg1;
@property(readonly, nonatomic) NSString *filePath; // @synthesize filePath;
- (void).cxx_destruct;
- (long long)u6W:(id)arg1;
- (long long)u4p:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (void)x7P:(id)arg1;
- (void)s7O:(id)arg1;
- (_Bool)b1F:(id)arg1;
- (void)g0y:(id)arg1;
- (void)reset;
@property(nonatomic) _Bool isL48; // @dynamic isL48;
- (id)description;
@property(readonly, nonatomic) double a2V; // @dynamic a2V;
@property(readonly, nonatomic) unsigned long long fileSize; // @dynamic fileSize;
@property(readonly, nonatomic) NSDate *creationDate; // @dynamic creationDate;
@property(readonly, nonatomic) NSDate *modificationDate; // @dynamic modificationDate;
@property(readonly, nonatomic) NSString *fileName; // @dynamic fileName;
@property(readonly, nonatomic) NSDictionary *fileAttributes; // @dynamic fileAttributes;
- (id)initWithFilePath:(id)arg1;

@end

