//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "o2m.h"

#import "m31.h"

@class NSMutableArray, NSMutableDictionary, NSString;

@interface q2N : o2m <m31>
{
    unsigned long long u7f;
    NSString *c4r;
    char *x1j;
    unsigned long long j2u;
    NSString *o3L;
    char *_pid;
    unsigned long long z8O;
    _Bool _c9d;
    NSMutableArray *x9y;
    NSMutableDictionary *d63;
    _Bool _m37;
}

+ (id)sharedInstance;
+ (unsigned long long)w2g:(id)arg1;
+ (void)getRed:(double *)arg1 green:(double *)arg2 blue:(double *)arg3 l4u:(id)arg4;
+ (void)m1o;
+ (void)j1W;
@property _Bool m37; // @synthesize m37=_m37;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *f7q;
- (void)z5W:(id)arg1;
- (void)h8I;
- (void)r4B;
- (void)n49;
- (void)c45:(id)arg1;
- (void)g0u:(unsigned long long)arg1 context:(int)arg2;
- (void)g0u:(unsigned long long)arg1;
- (void)setForegroundColor:(id)arg1 backgroundColor:(id)arg2 w05:(id)arg3;
- (void)setForegroundColor:(id)arg1 backgroundColor:(id)arg2 forFlag:(unsigned long long)arg3 context:(int)arg4;
- (void)setForegroundColor:(id)arg1 backgroundColor:(id)arg2 forFlag:(unsigned long long)arg3;
@property _Bool c9d;
- (void)z3O;
- (id)init;

// Remaining properties
@property(retain, nonatomic) id <i2o> b9L;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) struct dispatch_queue_s *n50;
@property(readonly) Class superclass;

@end

