//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableSet;

@interface s4E : NSObject
{
    int _lock;
    NSMutableSet *w7X;
}

- (void).cxx_destruct;
- (_Bool)f25:(unsigned long long)arg1;
@property(readonly, copy) NSArray *a0Y;
- (void)i6H:(unsigned long long)arg1;
- (void)d2G:(unsigned long long)arg1;
- (id)init;

@end

