//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UILabel, UITextField;

__attribute__((visibility("hidden")))
@interface s58 : UIViewController
{
    UITextField *j0r;
    UITextField *q0Z;
    UILabel *n0M;
}

- (void).cxx_destruct;
- (void)s48:(id)arg1;
- (void)u0U:(id)arg1;
- (void)h9R:(id)arg1;
- (id)d1L;
- (id)h7q;
- (id)userDefaults;
- (void)viewDidLoad;

@end

