//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UILabel, UITextField;

__attribute__((visibility("hidden")))
@interface u44 : UIViewController
{
    UITextField *f3z;
    UITextField *a8l;
    UILabel *q8Y;
}

- (void).cxx_destruct;
- (void)d2T:(id)arg1;
- (void)i5H:(id)arg1;
- (void)c8W:(id)arg1;
- (id)t1o;
- (id)m4s;
- (id)userDefaults;
- (void)viewDidLoad;

@end

