//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "i2o.h"

@class NSArray, NSString, s4E;

@interface v3K : NSObject <i2o>
{
    s4E *l7H;
}

- (void).cxx_destruct;
- (id)b3F:(id)arg1;
- (_Bool)p7b1:(unsigned long long)arg1;
@property(readonly, copy) NSArray *whitelist;
- (void)g5T:(unsigned long long)arg1;
- (void)c5v:(unsigned long long)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

