//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface y4v : NSObject
{
}

+ (void)x8d;
+ (void)k2Y:(struct __asl_object_s *)arg1;
+ (void)h00:(struct __asl_object_s *)arg1;
+ (void)setV1S:(unsigned long long)arg1;
+ (unsigned long long)v1S;
+ (void)stop;
+ (void)start;
+ (void)initialize;

@end

