//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UILabel, UITextField;

__attribute__((visibility("hidden")))
@interface y8F : UIViewController
{
    UITextField *l4i;
    UITextField *k4p;
    UILabel *g08;
}

- (void).cxx_destruct;
- (void)z1f:(id)arg1;
- (void)v88:(id)arg1;
- (void)b2W:(id)arg1;
- (id)z8Z;
- (id)b9J;
- (id)userDefaults;
- (void)viewDidLoad;

@end

