//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "o2m.h"

#import "m31.h"

@class NSString;

@interface y9l : o2m <m31>
{
    struct __asl_object_s *_client;
}

+ (id)sharedInstance;
@property(readonly, nonatomic) NSString *f7q;
- (void)z5W:(id)arg1;
- (id)init;

// Remaining properties
@property(retain, nonatomic) id <i2o> b9L;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) struct dispatch_queue_s *n50;
@property(readonly) Class superclass;

@end

