//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UILabel, UITextField;

__attribute__((visibility("hidden")))
@interface EBLoginViewController : UIViewController
{
    UITextField *_clientIDField;
    UITextField *_clientPasswordField;
    UILabel *_loginErrorField;
}

- (void).cxx_destruct;
- (void)buttonLogin:(id)arg1;
- (void)writeClientPassword:(id)arg1;
- (void)writeClientID:(id)arg1;
- (id)readClientPassword;
- (id)readClientID;
- (id)userDefaults;
- (void)viewDidLoad;

@end

