#!/bin/bash

set -e

# General build options
WORKSPACE="iOSClassGuard OpenSourceBar.xcworkspace"
# PROJECT=YourProject.xcodeproj
SCHEME="ExampleBankingApp"
CONFIGURATION=Release

# Additional build options
XCODEBUILD_OPTS=""
CLASS_GUARD_OPTS="-i IgnoredSymbol -F !ExcludedClass"

# In case of using Xcode >= 6 and SDK >= 8
CLASS_GUARD_OPTS_SDK="--sdk-root /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk"
# CLASS_GUARD_OPTS_SDK="$CLASS_GUARD_OPTS_SDK --sdk-ios iphonesimulator"

####################################################
# BUILD SCRIPT STARTS HERE
####################################################

# Just in case
echo "WARNING: This will wipe all your not commited changes in your repository"
echo "Press Ctrl-C to Cancel or Enter to proceed."
read

function echo_and_run() {
    echo "$@"
    "$@"
}

# Jump to directory where obfuscate script is located
pushd $(dirname $0)

# # Symbols file path
SYMBOLS_FILE="$PWD/symbols.h"

# Clean current workspace
echo_and_run git reset --hard
echo_and_run git clean -fdx

# Just in case: wipe build/
rm -rf build/ build.obf/ headers/ headers.obf/

# Automatically detect PODS
[[ -f Podfile ]] && [[ ! -f Pods/Manifest.lock ]] && pod install
[[ -f Pods/Pods.xcodeproj/project.pbxproj ]] && CLASS_GUARD_OPTS="$CLASS_GUARD_OPTS -P Pods/Pods.xcodeproj/project.pbxproj"

echo_and_run xcodebuild \
	-workspace "$WORKSPACE" \
	-scheme $SCHEME \
	-configuration $CONFIGURATION \
	-sdk iphonesimulator \
    clean build \
    OBJROOT="$PWD/build/" \
    SYMROOT="$PWD/build/" |\
    xcpretty

# Obfuscate project
appsNumber=0;
while read app
do
    if ((appsNumber > 0))
    then
        echo ""
        echo ""
        echo "You cannot use this tool when there is more than one .app file in products. Otherwise, only the first one will be used for obfuscation."
        echo ""
        echo ""
        exit
    fi
    ((appsNumber+=1))

    TARGET=$(basename "$app" .app)
    
    echo_and_run class-dump -H -o headers "$app/$TARGET"

	echo "Obfuscating $TARGET in $app..."
    echo_and_run ios-class-guard \
        $CLASS_GUARD_OPTS_SDK \
        $CLASS_GUARD_OPTS \
        -O "$SYMBOLS_FILE" \
        "$app/$TARGET"
done < <(find build/ -name '*.app')

# Insert SYMBOLS_FILE to all .pch found in project
echo_and_run find . -iname '*-Prefix.pch' -exec sed -i .bak '1i\
'"#import \"$SYMBOLS_FILE\"
" "{}" \;

echo_and_run xcodebuild \
	-workspace "$WORKSPACE" \
	-scheme $SCHEME \
	-configuration $CONFIGURATION \
	-sdk iphonesimulator \
    clean build \
    OBJROOT="$PWD/build.obf/" \
    SYMROOT="$PWD/build.obf/" |\
    xcpretty

appsNumber=0;
while read app
do
    if ((appsNumber > 0))
    then
        echo ""
        echo ""
        echo "You cannot use this tool when there is more than one .app file in products. Otherwise, only the first one will be used for obfuscation."
        echo ""
        echo ""
        exit
    fi
    ((appsNumber+=1))

    TARGET=$(basename "$app" .app)
    
    echo_and_run class-dump -H -o headers.obf "$app/$TARGET"

done < <(find build.obf/ -name '*.app')