# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Kiwi' do

end

target 'KiwiTests' do

end

target :KiwiTests, :exclusive => true do
  pod 'Kiwi', '~> 2.3.1'
end

